// Fragevorlage:
// {
//     category: "Toleranzen",
//     level: "N",
//     frage: "Frage",
//     fragebild: [],
//     fragebild_2: [],
//     antwort: "Antwort",
//     erklaerung: "Erklärung",
//     beispiel: "",
//     beispiel_bild: [],
//     beispiel_2: "",
//     beispiel_bild_2: []
// }

const questions_data = [

    // ==========================================
    // KATEGORIE: Wärmebehandlung
    // ==========================================


    {
        category: "Wärmebehandlung",
        level: "N",
        frage: "Was ist Allgemein der Zweck einer Wärmebehandlung?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Die Eigenschaften von Stahl gezielt zu verändern.",
        erklaerung: "\nZum Beispiel Härte, Zähigkeit, Festigkeit, Sprödigkeit, Verschleißfestigkeit oder Bearbeitbarkeit.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },


    {
        category: "Wärmebehandlung",
        level: "N",
        frage: "In welche 3 Hauptbereiche wird die Wärmebehandlung von Stahl eingeteilt?",
        fragebild: [],
        fragebild_2: [],
        antwort: "- Glühen,\n- Härten,\n- Vergüten.",
        erklaerung: "\nBeim **Glühen** werden beispielsweise Spannungen abgebaut oder die Bearbeitbarkeit verbessert.\n\nBeim **Härten** werden Härte und Verschleißfestigkeit erhöht.\n\nBeim **Vergüten** werden hohe Festigkeit und gute Zähigkeit kombiniert.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },

    {
        category: "Wärmebehandlung",
        level: "N",
        frage: "Aus welchen drei Schritten besteht der grundlegende Ablauf jeder Wärmebehandlung?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Erwärmen,\n- Halten (auf Temperatur),\n- Abkühlen.",
        erklaerung: "\nDieser dreistufige Ablauf ist universell. Die genauen Temperaturen, Haltezeiten und Abkühlgeschwindigkeiten bestimmen das Endergebnis.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Wärmebehandlung",
        level: "V",
        frage: "Wie wird das innere Gefüge (Atomanordnung) des Stahls bei der Wärmebehandlung gezielt verändert?",
        fragebild: [],
        fragebild_2: [],
        antwort: " Durch unterschiedliche Temperaturen und Abkühlgeschwindigkeiten.",
        erklaerung: "\nDie Höhe der Temperatur bestimmt die Beweglichkeit der Atome und die Gefügeumwandlung, während die Abkühlgeschwindigkeit darüber entscheidet, ob sich das ursprüngliche Gefüge zurückbildet oder ein neues Gefüge (z. B. Martensit) entsteht.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },

    // ==========================================
    // KATEGORIE: Glühen
    // ==========================================
    {
        category: "Glühen",
        level: "N",
        frage: "Was passiert grundlegend beim **Glühen** von Stahl?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Glühen verändert die Gefügestruktur und somit die Werkstoffeigenschaften.",
        erklaerung: "\nGlühverfahren unterscheiden sich vor allem in der Höhe der Temperatur und der Haltezeit.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Glühen",
        level: "N",
        frage: "Was ist das Ziel des **Rekristallisationsglühens** und wann wird es angewendet?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Ziel: Beseitigt die Folgen einer starken Kaltumformung.\n\nAnwendung:\nBeisppielsweise nach dem Tiefziehen, Biegen oder Walzen.",
        erklaerung: "\nDurch das Rekristallisationsglühen wird der Stahl wieder besser verformbar und die durch Kaltverfestigung entstandene hohe Festigkeit/Sprödigkeit nimmt ab.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Glühen",
        level: "N",
        frage: "Was ist das Ziel des **Weichglühens** und wann wird es angewendet?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Ziel:\nVerringert die Härte des Stahls und verbessert die Zerspanbarkeit.\n\nAnwendung:\nBeseitigen von harten Stellen (z. B. nach dem Schweißen) oder um gehärtete Werkstücke wieder bearbeitbar zu machen.",
        erklaerung: "\nDurch das Weichglühen lässt sich der Stahl mit spanenden Verfahren (Drehen, Fräsen, Bohren) wesentlich leichter und werkzeugschonender verarbeiten.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Glühen",
        level: "N",
        frage: "Was ist das Ziel des **Spannungsarmglühens** und warum wird es durchgeführt?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Ziel:\nBaut innere Eigenspannungen ab.\n\nAnwendung:\nNach thermischen Prozessen wie Gießen oder Schweißen.",
        erklaerung: "\nInnerlich verspannte Werkstücke werden spannungsarm geglüht, damit sie sich bei der späteren Bearbeitung oder Nutzung nicht verziehen.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Glühen",
        level: "N",
        frage: "Was bewirkt das **Normalglühen** und wo wird es angewendet?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Ziel:\nErzeugt ein feinkörniges und gleichmäßiges Gefüge zur Verbesserung von Festigkeit und Zähigkeit.\n\nAnwendung:\nBeispilesweise bei Baustählen, Schmiedeteilen und Stahlgussteilen.",
        erklaerung: "\nUnregelmäßige oder grobkörnige Gefüge, die durch vorherige Fertigungsschritte entstanden sind, werden wieder ausgeglichen.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Glühen",
        level: "N",
        frage: "Was versteht man unter **Diffusionsglühen** und wie funktioniert es?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Ziel:\nEs verringert Seigerungen (Konzentrationsunterschiede von Legierungselementen).\n\nAnwendung:\nBeispielsweise bei Stahlblöcken und Stahlgussteilen direkt nach dem Gießen.",
        erklaerung: "\nDurch die sehr hohe Temperatur und lange Haltezeit können die Atome im Werkstoff stärker wandern (diffundieren) und sich gleichmäßiger im Kristallgitter verteilen.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Glühen",
        level: "N",
        frage: "Was versteht man unter **Seigerungen**?",
        fragebild: [],
        fragebild_2: [],
        antwort: " Seigerungen sind Konzentrationsunterschiede von Legierungselementen im Werkstoff.",
        erklaerung: "\nSeigerungen sind unerwünscht,\nMan will ja, dass die Legierungselemente gleichmäßig im Werkstoff verteilt sind.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },

    // ==========================================
    // KATEGORIE: Härten
    // ==========================================
    {
        category: "Härten",
        level: "N",
        frage: "Wie ist der Begriff 'Härte' definiert?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Härte ist der Widerstand gegen das Eindringen eines anderen, härteren Körpers.",
        erklaerung: "\nDiese Eigenschaft ist entscheidend für den Verschleißschutz von Bauteilen.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Härten",
        level: "N",
        frage: "Was sind die ZIEL-Eigenschaften beim Härten von Stahl und welche Begleiterscheinung tritt auf?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Ziele: Erhöhung von:\n- Härte,\n- Verschleißfestigkeit und\n- Festigkeit.\n\nBegleiterscheinung: Die Sprödigkeit steigt.",
        erklaerung: "\nWeil der Stahl durch das reine Härten sehr spröde wird, muss er anschließend meist angelassen werden.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Härten",
        level: "N",
        frage: "Welche Grundvoraussetzung hinsichtlich des Kohlenstoffgehalts (C-Gehalt) muss für das normale Härten erfüllt sein?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Der Stahl muss mindestens ca. 0,2 % Kohlenstoff enthalten.",
        erklaerung: "\nStähle mit weniger als 0,2 % C erreichen beim normalen Härten nur eine sehr geringe Härte.\nDaher müssen sie vorher aufgekohlt werden (z. B. Einsatzhärten).\n\nMit zunehmendem C-Gehalt steigt die Härtbarkeit, aber auch die Rissgefahr beim Schweißen.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Härten",
        level: "N",
        frage: "Auf welche Temperatur wird Stahl beim Härten üblicherweise erwärmt?",
        fragebild: [],
        fragebild_2: [],
        antwort: "800 °C – 900 °C.",
        erklaerung: "\nDie Erwärmung erfolgt in einem Ofen oder mit einer Flamme.\nDie genaue Temperatur hängt von der Stahlart ab.\n\nHochlegierte Stähle haben Härtetemperaturen bis zu 1100 °C",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },

    {
        category: "Härten",
        level: "V",
        frage: "Was ändert sich im Stahl beim Erwärmen auf Härtetemperatur?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Die Gefüge-Struktur des Stahls dehnt sich aus und die Anordnung der Atome im Kristallgitter verändert sich.\n\nDie Kohlenstoffatome wandern in die Zwischenräume des Gitters.",
        erklaerung: "\nWenn der Stahl wieder **langsam** abkühlt, zieht sich das Gitter zusammen und die Kohlenstoffatome werden wieder aus den Zwischenräumen verdrängt.\n\nNichts würde sich ändern, wenn der Stahl langsam abkühlt.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Härten",
        level: "N",
        frage: "Was versteht man unter **Abschrecken**?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Abschrecken = schnelles Abkühlen in Medien wie Wasser, Öl oder Luft.",
        erklaerung: "\nAbschrecken **verhindert**, dass sich das Gefüge vollständig in seinen Ursprungszustand zurückbildet.\n\nDas harte Gefüge **Martensit** entsteht.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },


    {
        category: "Härten",
        level: "V",
        frage: "Warum entsteht beim Abschrecken das harte Gefüge **Martensit**?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Die Kohlenstoffatome sind zu langsam, um die Zwischenräume des Gitters zu verlassen, und werden eingesperrt.",
        erklaerung: "\nBeim Erhitzen dehnt sich das Eisengitter aus und C-Atome wandern in die Zwischenräume.\nBeim Abschrecken zieht sich das Gitter blitzschnell zusammen, sperrt die C-Atome ein und verzerrt sich stark.\nDieses innerlich verspannte Gitter nennt man Martensit.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Härten",
        level: "N",
        frage: "Welche Gefahren bestehen bei zu schnellem oder ungeeignetem Abschrecken beim Härten?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Es kann zu **Verzug, Härterissen** und hohen **inneren Spannungen** im Bauteil kommen.",
        erklaerung: "\nDeshalb muss das Abschreckmedium (Wasser, Öl oder Luft) genau auf die jeweilige Stahlart abgestimmt sein.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Härten",
        level: "N",
        frage: "Was ist der Zweck des **Anlassens** nach dem Härten?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Anlassen verringert die Sprödigkeit und innere Spannungen. Die Zähigkeit nimmt zu.",
        erklaerung: "\nDie beim Härten gewonnene Härte nimmt beim Anlassen nur geringfügig ab, aber das Bauteil verliert seine gefährliche Sprödigkeit.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Härten",
        level: "N",
        frage: "Was ist der grundsätzliche Unterschied zwischen **Durchhärten** und **Randschichthärten**?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Beim Durchhärten wird das gesamte Werkstück gehärtet.\n\nBeim Randschichthärten wird nur die äußere Randschicht hart, während der Kern zäh bleibt.",
        erklaerung: "\nDurchhärten: z. B. Wälzlagerteile, Schmiedewerkzeuge.\n\nRandschichthärten: z. B. Zahnräder, Wellen, Gleitbahnen.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Härten",
        level: "N",
        frage: "Nenne 4 wichtige Verfahren des Randschichthärtens.",
        fragebild: [],
        fragebild_2: [],
        antwort: "- Induktionshärten,\n- Flammhärten,\n- Laserhärten,\n- Einsatzhärten,\n- Nitrieren (Sonderfall).",
        erklaerung: "\nBei Induktions-, Flamm- und Laserhärten wird die Oberfläche lokal schnell erwärmt und abgeschreckt.\nBeim Einsatzhärten wird kohlenstoffarmer Stahl vor dem Härten an der Oberfläche aufgekohlt.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },

    {
        category: "Härten",
        level: "N",
        frage: "Was versteht man unter **Aufkohlen** beim Einsatzhärten?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Aufkohlen ist das Anreichern der Oberfläche mit Kohlenstoff.",
        erklaerung: "\nDadurch entsteht eine kohlenstoffreiche Randschicht, die sich Härten lässt.\n\nAnreichern -> so heißt der Prozess, bei dem Kohlenstoff in die Oberfläche eindringt und sich dort anreichern.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },

    {
        category: "Härten",
        level: "N",
        frage: "Wie funktioniert das **Nitrieren**?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Funktion:\nAnreichern der Randschicht mit Stickstoff bei ca. 500–550 °C.",
        erklaerung: "\nDurch die Stickstoffanlagerung entstehen sehr harte Nitride (bis 1200 HV bei 0,1–0,7 mm Tiefe).",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "Nitride sind Stickstoffverbindungen.",
        beispiel_bild_2: [],
    },

    {
        category: "Härten",
        level: "N",
        frage: "Welche Vor- und Nachteile bietet Nitrieren?",
        fragebild: [],
        fragebild_2: [],
        antwort: "\nVorteil:\n- Sehr geringer Verzug.\n- kein Abschrecken nötig\n- Werstücke können vorher fertig bearbeitet werden.\n\nNachteil:\n- Dünne, spröde Randschicht ist stößempfindlich.",
        erklaerung: "\nDa kein Abschrecken nötig ist, können Bauteile vorher fertig bearbeitet werden.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },

    {
        category: "Härten",
        level: "N",
        frage: "Nitrieren: Wie dick ist die harte Randschicht?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Nur wenige Zehntel Millimeter\n(oftmals 0,1–0,7 mm).",
        erklaerung: "",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },


    // ==========================================
    // KATEGORIE: Vergüten
    // ==========================================
    {
        category: "Vergüten",
        level: "N",
        frage: "Aus welchen zwei Wärmebehandlungsschritten setzt sich das **Vergüten** zusammen?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Vergüten = Härten + Anlassen bei einer höheren Temperatur.",
        erklaerung: "\nDurch die höhere Anlasstemperatur (500–700 °C) wird ein optimales Verhältnis zwischen Festigkeit und Zähigkeit eingestellt.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Vergüten",
        level: "N",
        frage: "Was ist das Hauptziel des Vergütens?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Herstellen von Bauteilen mit **hoher Festigkeit** und gleichzeitig **guter Zähigkeit**.",
        erklaerung: "\nVergüteter Stahl ist wesentlich dynamischer belastbar und weniger spröde als rein gehärteter Stahl.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Vergüten",
        level: "N",
        frage: "Welche Eigenschaften zeichnen Werkstücke nach dem Vergüten aus?",
        fragebild: [],
        fragebild_2: [],
        antwort: "Hohe Festigkeit, gute Zähigkeit und geringere Sprödigkeit als beim reinen Härten.",
        erklaerung: "\nDiese Eigenschaftskombination macht den Werkstoff widerstandsfähig gegen schlagende und wechselnde Beanspruchungen.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    },
    {
        category: "Vergüten",
        level: "N",
        frage: "Nenne typische Anwendungsbeispiele für vergütete Bauteile.",
        fragebild: [],
        fragebild_2: [],
        antwort: "\n- Wellen und Achsen,\n- Schrauben,\n- Kurbelwellen,\n- allgemeine hochbelastete Maschinenteile.",
        erklaerung: "\nÜberall dort, wo Bauteile hohen Kräften und Schwingungen ausgesetzt sind, ohne spröde zu brechen.",
        beispiel: "",
        beispiel_bild: [],
        beispiel_2: "",
        beispiel_bild_2: [],
    }
]


window.questionsData = questions_data;
